Add HTTP REST APIs to gatling-demostore, closes MISC-111
gatling/gatling-demostore pull request #4
Opened 2021-04-21 16:27 UTC by guilgaly

- I only added routes for categories and products; should be enough, but it won't be hard to add more routes if needed.
- The create/update routes are secured with a JWT, so we can use them for examples of storing the token in the Gatling session, using custom headers, that sort of things.
- I added a Postman collection which can be used to explore the API before writing test scenarios.

2021-04-21 19:17 UTC, slandelle requested changes
Interesting that you've integrated JWT. Looking forward to how to test this.

2021-04-21 19:17 UTC, slandelle commented on pom.xml
> +			<version>0.11.2</version>
Define a maven property so version is only defined once.

2021-04-22 07:29 UTC, guilgaly commented
About the Postman collection file: the file isn't used in the app, it's just here so that we can manually import it into Postman for testing, so I don't really see a problem with the spaces ion the file name?

That being said, it doesn't solve the question of allowing a student to easily explore the API before writing test scenarios... Adding a Swagger UI page might be ideal (nothing to install, easy to use) and it shouldn't take that long to do... I think I'll do that. 🤔

2021-04-22 09:53 UTC, guilgaly commented
I added the OpenAPI specification generation for the API. The library I used comes with Swagger UI packaged as a WebJar, so we also get that directly bundled with the app.

2021-04-22 14:53 UTC, slandelle requested changes

2021-04-22 14:53 UTC, slandelle commented on src/main/java/io/gatling/demostore/security/JwtRequestFilter.java
> +        System.out.println("[TEST] requestTokenHeader: " + requestTokenHeader);
nope

2021-04-22 15:39 UTC, guilgaly commented on src/main/java/io/gatling/demostore/security/JwtRequestFilter.java
> +        System.out.println("[TEST] requestTokenHeader: " + requestTokenHeader);
![56pvkw](https://user-images.githubusercontent.com/6560742/115743179-b6f49600-a391-11eb-8224-7ef59fb6413c.jpg)

2021-04-22 15:41 UTC, slandelle approved these changes

2021-04-23 09:26 UTC, merged